# Generated by Django 3.2.7 on 2025-03-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
