# Generated by Django 3.2.7 on 2025-03-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
