# Generated by Django 3.2.7 on 2025-03-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20250304_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
