# Generated by Django 3.2.7 on 2025-03-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20250304_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
