# Generated by Django 3.2.7 on 2025-03-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20250304_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={},
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employeedetails'),
        ),
    ]
