# Generated by Django 3.2.7 on 2025-03-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20250304_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
