# Generated by Django 3.2.7 on 2025-03-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_employeedetails_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='is_admin',
        ),
    ]
