# Generated by Django 3.2.7 on 2025-03-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_attendance_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
