# Generated by Django 3.2.7 on 2025-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_leaveapplication_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
