# Generated by Django 3.2.7 on 2025-03-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_alter_leaveapplication_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='username',
            field=models.CharField(choices=[('hr', ' product Manager'), ('hr', 'hr'), ('team leader', 'team leader')], max_length=150),
        ),
    ]
