# Generated by Django 3.2.7 on 2025-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_auto_20250307_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='role',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='role_type',
            field=models.CharField(choices=[('hr', ' product Manager'), ('hr', 'hr'), ('team leader', 'team leader')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
