# Generated by Django 3.2.7 on 2025-03-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='role_type',
            field=models.TextField(),
        ),
    ]
