# Generated by Django 5.1.7 on 2025-03-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_payroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='payment_date',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='hourly_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_earnings',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_working_hours',
            field=models.FloatField(),
        ),
    ]
