# Generated by Django 5.1.7 on 2025-03-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_remove_payroll_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_working_hours',
            field=models.IntegerField(),
        ),
    ]
