# Generated by Django 5.1.7 on 2025-03-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_alter_payroll_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payment_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterModelTable(
            name='payroll',
            table='attendance_payroll',
        ),
    ]
