# Generated by Django 5.1.7 on 2025-03-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_payroll_payment_date_alter_payroll_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
