# Generated by Django 5.1.7 on 2025-03-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_alter_payroll_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_working_hours',
        ),
        migrations.AddField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='payroll',
            table=None,
        ),
    ]
