# Generated by Django 5.1.7 on 2025-03-18 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_attendance_break_in_attendance_break_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='break_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='break_out',
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_in', models.DateTimeField(blank=True, null=True)),
                ('break_out', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
            ],
        ),
    ]
